//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPred.FuentesExternas.Isai.Services.ServiceRCON {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRCON.IRegistroContribuyentes")]
    public interface IRegistroContribuyentes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetCiudadesByNombre", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetCiudadesByNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetCiudadesByNombreRegistroContribuyen" +
            "tesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCiudades GetCiudadesByNombre(decimal codEstado, decimal codMunicipio, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/ExisteContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/ExisteContribuyenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/ExisteContribuyenteRegistroContribuyen" +
            "tesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        bool ExisteContribuyente(string rfc, string curp, string ife, System.Nullable<decimal> idpersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/InsertarContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/InsertarContribuyenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/InsertarContribuyenteRegistroContribuy" +
            "entesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente InsertarContribuyente(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseContribuyente, System.Nullable<decimal> idExpediente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/InsertarRepresentacion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/InsertarRepresentacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/InsertarRepresentacionRegistroContribu" +
            "yentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void InsertarRepresentacion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDatosRepresentacion dseDatosRep, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion tipo, string xml, string tipoDocumento, string listaIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/InsertarDireccion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/InsertarDireccionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/InsertarDireccionRegistroContribuyente" +
            "sExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones InsertarDireccion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/InsertarNotario", ReplyAction="http://tempuri.org/IRegistroContribuyentes/InsertarNotarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/InsertarNotarioRegistroContribuyentesE" +
            "xceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios InsertarNotario(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios dseNotarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/InsertarInmuebleDomicilioFiscal", ReplyAction="http://tempuri.org/IRegistroContribuyentes/InsertarInmuebleDomicilioFiscalRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/InsertarInmuebleDomicilioFiscalRegistr" +
            "oContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion InsertarInmuebleDomicilioFiscal(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion dseImnDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/ActualizarRepresentacion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/ActualizarRepresentacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/ActualizarRepresentacionRegistroContri" +
            "buyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void ActualizarRepresentacion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDatosRepresentacion dseDatosRep, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion tipo, string xml, string tipoDocumento, string listaIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/ActualizarContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/ActualizarContribuyenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/ActualizarContribuyenteRegistroContrib" +
            "uyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void ActualizarContribuyente(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseContribuyente, System.Nullable<decimal> idExpediente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/ActualizarDireccion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/ActualizarDireccionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/ActualizarDireccionRegistroContribuyen" +
            "tesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void ActualizarDireccion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/ActualizarNotario", ReplyAction="http://tempuri.org/IRegistroContribuyentes/ActualizarNotarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/ActualizarNotarioRegistroContribuyente" +
            "sExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void ActualizarNotario(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios dseNotario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/ActualizarInmuebleDomicilioFiscal", ReplyAction="http://tempuri.org/IRegistroContribuyentes/ActualizarInmuebleDomicilioFiscalRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/ActualizarInmuebleDomicilioFiscalRegis" +
            "troContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion ActualizarInmuebleDomicilioFiscal(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion dseImnDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentacion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentacionRegistroContribuye" +
            "ntesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void BorrarRepresentacion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseRep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentacionNotario", ReplyAction="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentacionNotarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentacionNotarioRegistroCon" +
            "tribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void BorrarRepresentacionNotario(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseRep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentante", ReplyAction="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentanteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/BorrarRepresentanteRegistroContribuyen" +
            "tesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void BorrarRepresentante(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente.RepresentantesDataTable dtRep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/BorrarDireccion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/BorrarDireccionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/BorrarDireccionRegistroContribuyentesE" +
            "xceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void BorrarDireccion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/BorrarDireccionContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/BorrarDireccionContribuyenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/BorrarDireccionContribuyenteRegistroCo" +
            "ntribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        void BorrarDireccionContribuyente(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionRegistroContribu" +
            "yentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccion(decimal idDireccion, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionDetalle", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionDetalleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionDetalleRegistroC" +
            "ontribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccionDetalle(decimal idDireccion, decimal idHistorico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionFiscal", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionFiscalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionFiscalRegistroCo" +
            "ntribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccionFiscal(decimal idPersonaInmueble, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionFiscalDetalle", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionFiscalDetalleRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosDireccionFiscalDetalleReg" +
            "istroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccionFiscalDetalle(decimal idPersonaInmueble, decimal idHistorico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosPersona", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosPersonaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosPersonaRegistroContribuye" +
            "ntesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosPersona(decimal idPersona, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosPersonaDetalle", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosPersonaDetalleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosPersonaDetalleRegistroCon" +
            "tribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosPersonaDetalle(decimal idPersona, decimal idHistorico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosRepresentacion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosRepresentacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosRepresentacionRegistroCon" +
            "tribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosRepresentacion(decimal idPersona, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosRepresentacionDetalle", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetHistoricosRepresentacionDetalleResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetHistoricosRepresentacionDetalleRegi" +
            "stroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosRepresentacionDetalle(System.Nullable<decimal> idRepresentante, System.Nullable<decimal> idRepresentado, decimal idHistorico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesByDatosPersonales", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesByDatosPersonalesResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesByDatosPersonalesRegi" +
            "stroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesByDatosPersonales(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoMaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetPersonaMoralByDatosPersonales", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetPersonaMoralByDatosPersonalesRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetPersonaMoralByDatosPersonalesRegist" +
            "roContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetPersonaMoralByDatosPersonales(string razonSocial, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesByDatosIdentificativo" +
            "s", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesByDatosIdentificativo" +
            "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesByDatosIdentificativo" +
            "sRegistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesByDatosIdentificativos(string rfc, string curp, string claveIfe, System.Nullable<decimal> iddocidentif, string valdocidentif, bool coincidenTodos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesMoralByDatosIdentific" +
            "ativos", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesMoralByDatosIdentific" +
            "ativosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesMoralByDatosIdentific" +
            "ativosRegistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesMoralByDatosIdentificativos(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetPersonaMoralByDatosIdentificativos", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetPersonaMoralByDatosIdentificativosR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetPersonaMoralByDatosIdentificativosR" +
            "egistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetPersonaMoralByDatosIdentificativos(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosPerson" +
            "ales", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosPerson" +
            "alesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosPerson" +
            "alesRegistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosPersonales(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoMaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosPerson" +
            "alesSIGASIIP", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosPerson" +
            "alesSIGASIIPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosPerson" +
            "alesSIGASIIPRegistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosPersonalesSIGASIIP(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoMaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesSimilares", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesSimilaresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesSimilaresRegistroCont" +
            "ribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DsePersonasSimilares GetContribuyentesSimilares(string nombre, string apellidoPaterno, string apellidoMaterno, string rfc, string curp, string claveife, string actividadPrincipal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosIdenti" +
            "ficativos", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosIdenti" +
            "ficativosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosIdenti" +
            "ficativosRegistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosIdentificativos(string rfc, string curp, string claveIfe, System.Nullable<decimal> idDocIdentif, string valDocIdentif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosIdenti" +
            "ficativosSIGASIIP", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosIdenti" +
            "ficativosSIGASIIPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetContribuyentesInmuebleByDatosIdenti" +
            "ficativosSIGASIIPRegistroContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosIdentificativosSIGASIIP(string rfc, string curp, string claveIfe, System.Nullable<decimal> idDocIdentif, string valDocIdentif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetInfoContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetInfoContribuyenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetInfoContribuyenteRegistroContribuye" +
            "ntesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente GetInfoContribuyente(decimal idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetDireccionesInmueble", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetDireccionesInmuebleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetDireccionesInmuebleRegistroContribu" +
            "yentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDireccionesInmueble GetDireccionesInmueble(decimal idInmueble);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetDireccionesContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetDireccionesContribuyenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetDireccionesContribuyenteRegistroCon" +
            "tribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente.DireccionesDataTable GetDireccionesContribuyente(decimal idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetRepresentacionContribuyente", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetRepresentacionContribuyenteResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetRepresentacionContribuyenteRegistro" +
            "ContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente.RepresentantesDataTable GetRepresentacionContribuyente(decimal idPersona, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion rep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetRepresentacionNotario", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetRepresentacionNotarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetRepresentacionNotarioRegistroContri" +
            "buyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios.RepresentantesDataTable GetRepresentacionNotario(decimal idPersona, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion rep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetNotariosByDatosPersonales", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetNotariosByDatosPersonalesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetNotariosByDatosPersonalesRegistroCo" +
            "ntribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseNotarios GetNotariosByDatosPersonales(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filApellidoMaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetNotariosByDatosIdentificativos", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetNotariosByDatosIdentificativosRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetNotariosByDatosIdentificativosRegis" +
            "troContribuyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseNotarios GetNotariosByDatosIdentificativos(System.Nullable<decimal> numNotario, System.Nullable<decimal> codEstado, string rfc, string curp, string ife, System.Nullable<decimal> idDocIdentif, string valDocIdentif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetInfoNotario", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetInfoNotarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetInfoNotarioRegistroContribuyentesEx" +
            "ceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios GetInfoNotario(decimal idPersona, bool infoExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetDatosRepresentacion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetDatosRepresentacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetDatosRepresentacionRegistroContribu" +
            "yentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDatosRepresentacion GetDatosRepresentacion(decimal idRepresentacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetDireccionById", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetDireccionByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetDireccionByIdRegistroContribuyentes" +
            "ExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones GetDireccionById(decimal idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetAsentamiento", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoRegistroContribuyentesE" +
            "xceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseAsentamientos GetAsentamiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoByEstado", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoByEstadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoByEstadoRegistroContrib" +
            "uyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseAsentamientos GetAsentamientoByEstado(System.Nullable<decimal> codEstado, System.Nullable<decimal> codCiudad, System.Nullable<decimal> codMunicipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoByNombre", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoByNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetAsentamientoByNombreRegistroContrib" +
            "uyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseAsentamientos GetAsentamientoByNombre(string nombre, System.Nullable<decimal> codEstado, System.Nullable<decimal> codCiudad, System.Nullable<decimal> codMunicipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetCiudad", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetCiudadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetCiudadRegistroContribuyentesExcepti" +
            "onFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCiudades GetCiudad(decimal codEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetCiudadByEstado", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetCiudadByEstadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetCiudadByEstadoRegistroContribuyente" +
            "sExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCiudades GetCiudadByEstado(decimal codEstado, decimal codMunicipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetMunicipios", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosRegistroContribuyentesExc" +
            "eptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseMunicipios GetMunicipios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosByEstado", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosByEstadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosByEstadoRegistroContribuy" +
            "entesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseMunicipios GetMunicipiosByEstado(decimal codEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosByNombre", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosByNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetMunicipiosByNombreRegistroContribuy" +
            "entesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseMunicipios GetMunicipiosByNombre(decimal codEstado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetEstados", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetEstadosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetEstadosRegistroContribuyentesExcept" +
            "ionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseEstados GetEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetCatalogos", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetCatalogosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetCatalogosRegistroContribuyentesExce" +
            "ptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCatalogos GetCatalogos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetColAsentByDelegacion", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetColAsentByDelegacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetColAsentByDelegacionRegistroContrib" +
            "uyentesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseColoniaAsentamiento GetColAsentByDelegacion(decimal idDelegacion, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistroContribuyentes/GetDomiciliosFiscales", ReplyAction="http://tempuri.org/IRegistroContribuyentes/GetDomiciliosFiscalesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.RegistroContribuyentes.Services.Negocio.RegistroContribuyentesException), Action="http://tempuri.org/IRegistroContribuyentes/GetDomiciliosFiscalesRegistroContribuy" +
            "entesExceptionFault", Name="RegistroContribuyentesException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.RegistroContribuyentes.Services." +
            "Negocio")]
        SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion GetDomiciliosFiscales(decimal idPersona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistroContribuyentesChannel : SIGAPred.FuentesExternas.Isai.Services.ServiceRCON.IRegistroContribuyentes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroContribuyentesClient : System.ServiceModel.ClientBase<SIGAPred.FuentesExternas.Isai.Services.ServiceRCON.IRegistroContribuyentes>, SIGAPred.FuentesExternas.Isai.Services.ServiceRCON.IRegistroContribuyentes {
        
        public RegistroContribuyentesClient() {
        }
        
        public RegistroContribuyentesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroContribuyentesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroContribuyentesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroContribuyentesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCiudades GetCiudadesByNombre(decimal codEstado, decimal codMunicipio, string nombre) {
            return base.Channel.GetCiudadesByNombre(codEstado, codMunicipio, nombre);
        }
        
        public bool ExisteContribuyente(string rfc, string curp, string ife, System.Nullable<decimal> idpersona) {
            return base.Channel.ExisteContribuyente(rfc, curp, ife, idpersona);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente InsertarContribuyente(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseContribuyente, System.Nullable<decimal> idExpediente) {
            return base.Channel.InsertarContribuyente(dseContribuyente, idExpediente);
        }
        
        public void InsertarRepresentacion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDatosRepresentacion dseDatosRep, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion tipo, string xml, string tipoDocumento, string listaIds) {
            base.Channel.InsertarRepresentacion(dseDatosRep, tipo, xml, tipoDocumento, listaIds);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones InsertarDireccion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir) {
            return base.Channel.InsertarDireccion(dseDir);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios InsertarNotario(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios dseNotarios) {
            return base.Channel.InsertarNotario(dseNotarios);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion InsertarInmuebleDomicilioFiscal(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion dseImnDir) {
            return base.Channel.InsertarInmuebleDomicilioFiscal(dseImnDir);
        }
        
        public void ActualizarRepresentacion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDatosRepresentacion dseDatosRep, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion tipo, string xml, string tipoDocumento, string listaIds) {
            base.Channel.ActualizarRepresentacion(dseDatosRep, tipo, xml, tipoDocumento, listaIds);
        }
        
        public void ActualizarContribuyente(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseContribuyente, System.Nullable<decimal> idExpediente) {
            base.Channel.ActualizarContribuyente(dseContribuyente, idExpediente);
        }
        
        public void ActualizarDireccion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir) {
            base.Channel.ActualizarDireccion(dseDir);
        }
        
        public void ActualizarNotario(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios dseNotario) {
            base.Channel.ActualizarNotario(dseNotario);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion ActualizarInmuebleDomicilioFiscal(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion dseImnDir) {
            return base.Channel.ActualizarInmuebleDomicilioFiscal(dseImnDir);
        }
        
        public void BorrarRepresentacion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseRep) {
            base.Channel.BorrarRepresentacion(dseRep);
        }
        
        public void BorrarRepresentacionNotario(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente dseRep) {
            base.Channel.BorrarRepresentacionNotario(dseRep);
        }
        
        public void BorrarRepresentante(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente.RepresentantesDataTable dtRep) {
            base.Channel.BorrarRepresentante(dtRep);
        }
        
        public void BorrarDireccion(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir) {
            base.Channel.BorrarDireccion(dseDir);
        }
        
        public void BorrarDireccionContribuyente(SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones dseDir) {
            base.Channel.BorrarDireccionContribuyente(dseDir);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccion(decimal idDireccion, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            return base.Channel.GetHistoricosDireccion(idDireccion, fechaDesde, fechaHasta);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccionDetalle(decimal idDireccion, decimal idHistorico) {
            return base.Channel.GetHistoricosDireccionDetalle(idDireccion, idHistorico);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccionFiscal(decimal idPersonaInmueble, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            return base.Channel.GetHistoricosDireccionFiscal(idPersonaInmueble, fechaDesde, fechaHasta);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosDireccionFiscalDetalle(decimal idPersonaInmueble, decimal idHistorico) {
            return base.Channel.GetHistoricosDireccionFiscalDetalle(idPersonaInmueble, idHistorico);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosPersona(decimal idPersona, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            return base.Channel.GetHistoricosPersona(idPersona, fechaDesde, fechaHasta);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosPersonaDetalle(decimal idPersona, decimal idHistorico) {
            return base.Channel.GetHistoricosPersonaDetalle(idPersona, idHistorico);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosRepresentacion(decimal idPersona, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            return base.Channel.GetHistoricosRepresentacion(idPersona, fechaDesde, fechaHasta);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseHistorico GetHistoricosRepresentacionDetalle(System.Nullable<decimal> idRepresentante, System.Nullable<decimal> idRepresentado, decimal idHistorico) {
            return base.Channel.GetHistoricosRepresentacionDetalle(idRepresentante, idRepresentado, idHistorico);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesByDatosPersonales(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoMaterno) {
            return base.Channel.GetContribuyentesByDatosPersonales(nombre, filtroNombre, apellidoPaterno, filtroApellidoPaterno, apellidoMaterno, filtroApellidoMaterno);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetPersonaMoralByDatosPersonales(string razonSocial, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtro) {
            return base.Channel.GetPersonaMoralByDatosPersonales(razonSocial, filtro);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesByDatosIdentificativos(string rfc, string curp, string claveIfe, System.Nullable<decimal> iddocidentif, string valdocidentif, bool coincidenTodos) {
            return base.Channel.GetContribuyentesByDatosIdentificativos(rfc, curp, claveIfe, iddocidentif, valdocidentif, coincidenTodos);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesMoralByDatosIdentificativos(string rfc) {
            return base.Channel.GetContribuyentesMoralByDatosIdentificativos(rfc);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetPersonaMoralByDatosIdentificativos(string rfc) {
            return base.Channel.GetPersonaMoralByDatosIdentificativos(rfc);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosPersonales(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoMaterno) {
            return base.Channel.GetContribuyentesInmuebleByDatosPersonales(nombre, filtroNombre, apellidoPaterno, filtroApellidoPaterno, apellidoMaterno, filtroApellidoMaterno);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosPersonalesSIGASIIP(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filtroApellidoMaterno) {
            return base.Channel.GetContribuyentesInmuebleByDatosPersonalesSIGASIIP(nombre, filtroNombre, apellidoPaterno, filtroApellidoPaterno, apellidoMaterno, filtroApellidoMaterno);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DsePersonasSimilares GetContribuyentesSimilares(string nombre, string apellidoPaterno, string apellidoMaterno, string rfc, string curp, string claveife, string actividadPrincipal) {
            return base.Channel.GetContribuyentesSimilares(nombre, apellidoPaterno, apellidoMaterno, rfc, curp, claveife, actividadPrincipal);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosIdentificativos(string rfc, string curp, string claveIfe, System.Nullable<decimal> idDocIdentif, string valDocIdentif) {
            return base.Channel.GetContribuyentesInmuebleByDatosIdentificativos(rfc, curp, claveIfe, idDocIdentif, valDocIdentif);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseContribuyentes GetContribuyentesInmuebleByDatosIdentificativosSIGASIIP(string rfc, string curp, string claveIfe, System.Nullable<decimal> idDocIdentif, string valDocIdentif) {
            return base.Channel.GetContribuyentesInmuebleByDatosIdentificativosSIGASIIP(rfc, curp, claveIfe, idDocIdentif, valDocIdentif);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente GetInfoContribuyente(decimal idPersona) {
            return base.Channel.GetInfoContribuyente(idPersona);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDireccionesInmueble GetDireccionesInmueble(decimal idInmueble) {
            return base.Channel.GetDireccionesInmueble(idInmueble);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente.DireccionesDataTable GetDireccionesContribuyente(decimal idPersona) {
            return base.Channel.GetDireccionesContribuyente(idPersona);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoContribuyente.RepresentantesDataTable GetRepresentacionContribuyente(decimal idPersona, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion rep) {
            return base.Channel.GetRepresentacionContribuyente(idPersona, rep);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios.RepresentantesDataTable GetRepresentacionNotario(decimal idPersona, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoRepresentacion rep) {
            return base.Channel.GetRepresentacionNotario(idPersona, rep);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseNotarios GetNotariosByDatosPersonales(string nombre, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filNombre, string apellidoPaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filApellidoPaterno, string apellidoMaterno, SIGAPred.RegistroContribuyentes.Services.Negocio.Enum.TipoFiltroLike filApellidoMaterno) {
            return base.Channel.GetNotariosByDatosPersonales(nombre, filNombre, apellidoPaterno, filApellidoPaterno, apellidoMaterno, filApellidoMaterno);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseNotarios GetNotariosByDatosIdentificativos(System.Nullable<decimal> numNotario, System.Nullable<decimal> codEstado, string rfc, string curp, string ife, System.Nullable<decimal> idDocIdentif, string valDocIdentif) {
            return base.Channel.GetNotariosByDatosIdentificativos(numNotario, codEstado, rfc, curp, ife, idDocIdentif, valDocIdentif);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoNotarios GetInfoNotario(decimal idPersona, bool infoExtra) {
            return base.Channel.GetInfoNotario(idPersona, infoExtra);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseDatosRepresentacion GetDatosRepresentacion(decimal idRepresentacion) {
            return base.Channel.GetDatosRepresentacion(idRepresentacion);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInfoDirecciones GetDireccionById(decimal idDireccion) {
            return base.Channel.GetDireccionById(idDireccion);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseAsentamientos GetAsentamiento() {
            return base.Channel.GetAsentamiento();
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseAsentamientos GetAsentamientoByEstado(System.Nullable<decimal> codEstado, System.Nullable<decimal> codCiudad, System.Nullable<decimal> codMunicipio) {
            return base.Channel.GetAsentamientoByEstado(codEstado, codCiudad, codMunicipio);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseAsentamientos GetAsentamientoByNombre(string nombre, System.Nullable<decimal> codEstado, System.Nullable<decimal> codCiudad, System.Nullable<decimal> codMunicipio) {
            return base.Channel.GetAsentamientoByNombre(nombre, codEstado, codCiudad, codMunicipio);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCiudades GetCiudad(decimal codEstado) {
            return base.Channel.GetCiudad(codEstado);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCiudades GetCiudadByEstado(decimal codEstado, decimal codMunicipio) {
            return base.Channel.GetCiudadByEstado(codEstado, codMunicipio);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseMunicipios GetMunicipios() {
            return base.Channel.GetMunicipios();
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseMunicipios GetMunicipiosByEstado(decimal codEstado) {
            return base.Channel.GetMunicipiosByEstado(codEstado);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseMunicipios GetMunicipiosByNombre(decimal codEstado, string municipio) {
            return base.Channel.GetMunicipiosByNombre(codEstado, municipio);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseEstados GetEstados() {
            return base.Channel.GetEstados();
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseCatalogos GetCatalogos() {
            return base.Channel.GetCatalogos();
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseColoniaAsentamiento GetColAsentByDelegacion(decimal idDelegacion, string nombre) {
            return base.Channel.GetColAsentByDelegacion(idDelegacion, nombre);
        }
        
        public SIGAPred.RegistroContribuyentes.Services.AccesoDatos.DseInmuebleDireccion GetDomiciliosFiscales(decimal idPersona) {
            return base.Channel.GetDomiciliosFiscales(idPersona);
        }
    }
}
