//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPred.FuentesExternas.Isai.Services.ServiceLC1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.1.78.2/fut/LineaCaptura_WS/GeneralLC/lineaCapturaGenWs_secureServer.php" +
        "?wsdl", ConfigurationName="ServiceLC1.ServicesPortType")]
    public interface ServicesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tr_lineaCapturaGeneral))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(detalleCamposMatriz))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.tr_lineaCapturaGeneral[] solicitaLineaCapturaGen(SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.tp_lineaCapturaGeneral pregunta);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.78.2/fut/LineaCaptura_WS/GeneralLC/lineaCapturaGenWs_secureServer.php" +
        "?wsdl")]
    public partial class tp_lineaCapturaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        private int intImpuestoField;
        
        private string referenciaField;
        
        private string fechaLimPPField;
        
        private int totalVField;
        
        private string conceptoField;
        
        private int numPeriodosField;
        
        private string usuarioGenField;
        
        private string ipField;
        
        private string cajaField;
        
        private string idliquidacionField;
        
        private string idpre_liquidaField;
        
        private string fpagoField;
        
        private string loteField;
        
        private int cuentasField;
        
        private detalleCamposMatriz[] arrayDatosField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public int intImpuesto {
            get {
                return this.intImpuestoField;
            }
            set {
                this.intImpuestoField = value;
                this.RaisePropertyChanged("intImpuesto");
            }
        }
        
        /// <remarks/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        public string fechaLimPP {
            get {
                return this.fechaLimPPField;
            }
            set {
                this.fechaLimPPField = value;
                this.RaisePropertyChanged("fechaLimPP");
            }
        }
        
        /// <remarks/>
        public int totalV {
            get {
                return this.totalVField;
            }
            set {
                this.totalVField = value;
                this.RaisePropertyChanged("totalV");
            }
        }
        
        /// <remarks/>
        public string concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("concepto");
            }
        }
        
        /// <remarks/>
        public int numPeriodos {
            get {
                return this.numPeriodosField;
            }
            set {
                this.numPeriodosField = value;
                this.RaisePropertyChanged("numPeriodos");
            }
        }
        
        /// <remarks/>
        public string usuarioGen {
            get {
                return this.usuarioGenField;
            }
            set {
                this.usuarioGenField = value;
                this.RaisePropertyChanged("usuarioGen");
            }
        }
        
        /// <remarks/>
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        /// <remarks/>
        public string caja {
            get {
                return this.cajaField;
            }
            set {
                this.cajaField = value;
                this.RaisePropertyChanged("caja");
            }
        }
        
        /// <remarks/>
        public string idliquidacion {
            get {
                return this.idliquidacionField;
            }
            set {
                this.idliquidacionField = value;
                this.RaisePropertyChanged("idliquidacion");
            }
        }
        
        /// <remarks/>
        public string idpre_liquida {
            get {
                return this.idpre_liquidaField;
            }
            set {
                this.idpre_liquidaField = value;
                this.RaisePropertyChanged("idpre_liquida");
            }
        }
        
        /// <remarks/>
        public string fpago {
            get {
                return this.fpagoField;
            }
            set {
                this.fpagoField = value;
                this.RaisePropertyChanged("fpago");
            }
        }
        
        /// <remarks/>
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        public int cuentas {
            get {
                return this.cuentasField;
            }
            set {
                this.cuentasField = value;
                this.RaisePropertyChanged("cuentas");
            }
        }
        
        /// <remarks/>
        public detalleCamposMatriz[] arrayDatos {
            get {
                return this.arrayDatosField;
            }
            set {
                this.arrayDatosField = value;
                this.RaisePropertyChanged("arrayDatos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.78.2/fut/LineaCaptura_WS/GeneralLC/lineaCapturaGenWs_secureServer.php" +
        "?wsdl")]
    public partial class detalleCamposMatriz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ctaoptpField;
        
        private string ctaaguaField;
        
        private string ctapredialField;
        
        private string ctarfcField;
        
        private string ctaestatalField;
        
        private string ctamercadoField;
        
        private string convenioField;
        
        private string ctaeconumField;
        
        private string nplacaField;
        
        private string numcreditoField;
        
        private string numfolioField;
        
        private string liquidacionField;
        
        private int periniField;
        
        private int perfinField;
        
        private int perayoField;
        
        private int pervenField;
        
        private string vencimField;
        
        private string impuestoField;
        
        private string derechoField;
        
        private string importe1Field;
        
        private string importe2Field;
        
        private string multaField;
        
        private string ivaField;
        
        private string cobranzaField;
        
        private string embargoField;
        
        private string recargo1Field;
        
        private string recargo2Field;
        
        private string otrosField;
        
        private string subsidioField;
        
        private string bonificaField;
        
        private string totalField;
        
        private string tdeclaField;
        
        private string tsaldoField;
        
        private string taplicField;
        
        private string fpagoField;
        
        private string pcanclField;
        
        private string totemp1Field;
        
        private string totemp2Field;
        
        private string actividadField;
        
        private string nparcField;
        
        private string hracobField;
        
        private string fraccionField;
        
        private string delegField;
        
        private string fmoveField;
        
        private string numelemField;
        
        private string tlicField;
        
        private string imprimeField;
        
        private string remesaField;
        
        private string lineacapField;
        
        private string id_pagoField;
        
        private int id_transf_electField;
        
        /// <remarks/>
        public string ctaoptp {
            get {
                return this.ctaoptpField;
            }
            set {
                this.ctaoptpField = value;
                this.RaisePropertyChanged("ctaoptp");
            }
        }
        
        /// <remarks/>
        public string ctaagua {
            get {
                return this.ctaaguaField;
            }
            set {
                this.ctaaguaField = value;
                this.RaisePropertyChanged("ctaagua");
            }
        }
        
        /// <remarks/>
        public string ctapredial {
            get {
                return this.ctapredialField;
            }
            set {
                this.ctapredialField = value;
                this.RaisePropertyChanged("ctapredial");
            }
        }
        
        /// <remarks/>
        public string ctarfc {
            get {
                return this.ctarfcField;
            }
            set {
                this.ctarfcField = value;
                this.RaisePropertyChanged("ctarfc");
            }
        }
        
        /// <remarks/>
        public string ctaestatal {
            get {
                return this.ctaestatalField;
            }
            set {
                this.ctaestatalField = value;
                this.RaisePropertyChanged("ctaestatal");
            }
        }
        
        /// <remarks/>
        public string ctamercado {
            get {
                return this.ctamercadoField;
            }
            set {
                this.ctamercadoField = value;
                this.RaisePropertyChanged("ctamercado");
            }
        }
        
        /// <remarks/>
        public string convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
                this.RaisePropertyChanged("convenio");
            }
        }
        
        /// <remarks/>
        public string ctaeconum {
            get {
                return this.ctaeconumField;
            }
            set {
                this.ctaeconumField = value;
                this.RaisePropertyChanged("ctaeconum");
            }
        }
        
        /// <remarks/>
        public string nplaca {
            get {
                return this.nplacaField;
            }
            set {
                this.nplacaField = value;
                this.RaisePropertyChanged("nplaca");
            }
        }
        
        /// <remarks/>
        public string numcredito {
            get {
                return this.numcreditoField;
            }
            set {
                this.numcreditoField = value;
                this.RaisePropertyChanged("numcredito");
            }
        }
        
        /// <remarks/>
        public string numfolio {
            get {
                return this.numfolioField;
            }
            set {
                this.numfolioField = value;
                this.RaisePropertyChanged("numfolio");
            }
        }
        
        /// <remarks/>
        public string liquidacion {
            get {
                return this.liquidacionField;
            }
            set {
                this.liquidacionField = value;
                this.RaisePropertyChanged("liquidacion");
            }
        }
        
        /// <remarks/>
        public int perini {
            get {
                return this.periniField;
            }
            set {
                this.periniField = value;
                this.RaisePropertyChanged("perini");
            }
        }
        
        /// <remarks/>
        public int perfin {
            get {
                return this.perfinField;
            }
            set {
                this.perfinField = value;
                this.RaisePropertyChanged("perfin");
            }
        }
        
        /// <remarks/>
        public int perayo {
            get {
                return this.perayoField;
            }
            set {
                this.perayoField = value;
                this.RaisePropertyChanged("perayo");
            }
        }
        
        /// <remarks/>
        public int perven {
            get {
                return this.pervenField;
            }
            set {
                this.pervenField = value;
                this.RaisePropertyChanged("perven");
            }
        }
        
        /// <remarks/>
        public string vencim {
            get {
                return this.vencimField;
            }
            set {
                this.vencimField = value;
                this.RaisePropertyChanged("vencim");
            }
        }
        
        /// <remarks/>
        public string impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }
        
        /// <remarks/>
        public string derecho {
            get {
                return this.derechoField;
            }
            set {
                this.derechoField = value;
                this.RaisePropertyChanged("derecho");
            }
        }
        
        /// <remarks/>
        public string importe1 {
            get {
                return this.importe1Field;
            }
            set {
                this.importe1Field = value;
                this.RaisePropertyChanged("importe1");
            }
        }
        
        /// <remarks/>
        public string importe2 {
            get {
                return this.importe2Field;
            }
            set {
                this.importe2Field = value;
                this.RaisePropertyChanged("importe2");
            }
        }
        
        /// <remarks/>
        public string multa {
            get {
                return this.multaField;
            }
            set {
                this.multaField = value;
                this.RaisePropertyChanged("multa");
            }
        }
        
        /// <remarks/>
        public string iva {
            get {
                return this.ivaField;
            }
            set {
                this.ivaField = value;
                this.RaisePropertyChanged("iva");
            }
        }
        
        /// <remarks/>
        public string cobranza {
            get {
                return this.cobranzaField;
            }
            set {
                this.cobranzaField = value;
                this.RaisePropertyChanged("cobranza");
            }
        }
        
        /// <remarks/>
        public string embargo {
            get {
                return this.embargoField;
            }
            set {
                this.embargoField = value;
                this.RaisePropertyChanged("embargo");
            }
        }
        
        /// <remarks/>
        public string recargo1 {
            get {
                return this.recargo1Field;
            }
            set {
                this.recargo1Field = value;
                this.RaisePropertyChanged("recargo1");
            }
        }
        
        /// <remarks/>
        public string recargo2 {
            get {
                return this.recargo2Field;
            }
            set {
                this.recargo2Field = value;
                this.RaisePropertyChanged("recargo2");
            }
        }
        
        /// <remarks/>
        public string otros {
            get {
                return this.otrosField;
            }
            set {
                this.otrosField = value;
                this.RaisePropertyChanged("otros");
            }
        }
        
        /// <remarks/>
        public string subsidio {
            get {
                return this.subsidioField;
            }
            set {
                this.subsidioField = value;
                this.RaisePropertyChanged("subsidio");
            }
        }
        
        /// <remarks/>
        public string bonifica {
            get {
                return this.bonificaField;
            }
            set {
                this.bonificaField = value;
                this.RaisePropertyChanged("bonifica");
            }
        }
        
        /// <remarks/>
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        public string tdecla {
            get {
                return this.tdeclaField;
            }
            set {
                this.tdeclaField = value;
                this.RaisePropertyChanged("tdecla");
            }
        }
        
        /// <remarks/>
        public string tsaldo {
            get {
                return this.tsaldoField;
            }
            set {
                this.tsaldoField = value;
                this.RaisePropertyChanged("tsaldo");
            }
        }
        
        /// <remarks/>
        public string taplic {
            get {
                return this.taplicField;
            }
            set {
                this.taplicField = value;
                this.RaisePropertyChanged("taplic");
            }
        }
        
        /// <remarks/>
        public string fpago {
            get {
                return this.fpagoField;
            }
            set {
                this.fpagoField = value;
                this.RaisePropertyChanged("fpago");
            }
        }
        
        /// <remarks/>
        public string pcancl {
            get {
                return this.pcanclField;
            }
            set {
                this.pcanclField = value;
                this.RaisePropertyChanged("pcancl");
            }
        }
        
        /// <remarks/>
        public string totemp1 {
            get {
                return this.totemp1Field;
            }
            set {
                this.totemp1Field = value;
                this.RaisePropertyChanged("totemp1");
            }
        }
        
        /// <remarks/>
        public string totemp2 {
            get {
                return this.totemp2Field;
            }
            set {
                this.totemp2Field = value;
                this.RaisePropertyChanged("totemp2");
            }
        }
        
        /// <remarks/>
        public string actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        public string nparc {
            get {
                return this.nparcField;
            }
            set {
                this.nparcField = value;
                this.RaisePropertyChanged("nparc");
            }
        }
        
        /// <remarks/>
        public string hracob {
            get {
                return this.hracobField;
            }
            set {
                this.hracobField = value;
                this.RaisePropertyChanged("hracob");
            }
        }
        
        /// <remarks/>
        public string fraccion {
            get {
                return this.fraccionField;
            }
            set {
                this.fraccionField = value;
                this.RaisePropertyChanged("fraccion");
            }
        }
        
        /// <remarks/>
        public string deleg {
            get {
                return this.delegField;
            }
            set {
                this.delegField = value;
                this.RaisePropertyChanged("deleg");
            }
        }
        
        /// <remarks/>
        public string fmove {
            get {
                return this.fmoveField;
            }
            set {
                this.fmoveField = value;
                this.RaisePropertyChanged("fmove");
            }
        }
        
        /// <remarks/>
        public string numelem {
            get {
                return this.numelemField;
            }
            set {
                this.numelemField = value;
                this.RaisePropertyChanged("numelem");
            }
        }
        
        /// <remarks/>
        public string tlic {
            get {
                return this.tlicField;
            }
            set {
                this.tlicField = value;
                this.RaisePropertyChanged("tlic");
            }
        }
        
        /// <remarks/>
        public string imprime {
            get {
                return this.imprimeField;
            }
            set {
                this.imprimeField = value;
                this.RaisePropertyChanged("imprime");
            }
        }
        
        /// <remarks/>
        public string remesa {
            get {
                return this.remesaField;
            }
            set {
                this.remesaField = value;
                this.RaisePropertyChanged("remesa");
            }
        }
        
        /// <remarks/>
        public string lineacap {
            get {
                return this.lineacapField;
            }
            set {
                this.lineacapField = value;
                this.RaisePropertyChanged("lineacap");
            }
        }
        
        /// <remarks/>
        public string id_pago {
            get {
                return this.id_pagoField;
            }
            set {
                this.id_pagoField = value;
                this.RaisePropertyChanged("id_pago");
            }
        }
        
        /// <remarks/>
        public int id_transf_elect {
            get {
                return this.id_transf_electField;
            }
            set {
                this.id_transf_electField = value;
                this.RaisePropertyChanged("id_transf_elect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.78.2/fut/LineaCaptura_WS/GeneralLC/lineaCapturaGenWs_secureServer.php" +
        "?wsdl")]
    public partial class tr_lineaCapturaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int intImpuestoField;
        
        private string referenciaField;
        
        private string lineaCapturaField;
        
        private string rafagaPagoField;
        
        private System.DateTime fcobroField;
        
        private string cajaField;
        
        private string partidaField;
        
        private string dagidField;
        
        private int errorField;
        
        private string error_descripcionField;
        
        /// <remarks/>
        public int intImpuesto {
            get {
                return this.intImpuestoField;
            }
            set {
                this.intImpuestoField = value;
                this.RaisePropertyChanged("intImpuesto");
            }
        }
        
        /// <remarks/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        public string lineaCaptura {
            get {
                return this.lineaCapturaField;
            }
            set {
                this.lineaCapturaField = value;
                this.RaisePropertyChanged("lineaCaptura");
            }
        }
        
        /// <remarks/>
        public string rafagaPago {
            get {
                return this.rafagaPagoField;
            }
            set {
                this.rafagaPagoField = value;
                this.RaisePropertyChanged("rafagaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fcobro {
            get {
                return this.fcobroField;
            }
            set {
                this.fcobroField = value;
                this.RaisePropertyChanged("fcobro");
            }
        }
        
        /// <remarks/>
        public string caja {
            get {
                return this.cajaField;
            }
            set {
                this.cajaField = value;
                this.RaisePropertyChanged("caja");
            }
        }
        
        /// <remarks/>
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
                this.RaisePropertyChanged("partida");
            }
        }
        
        /// <remarks/>
        public string dagid {
            get {
                return this.dagidField;
            }
            set {
                this.dagidField = value;
                this.RaisePropertyChanged("dagid");
            }
        }
        
        /// <remarks/>
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        public string error_descripcion {
            get {
                return this.error_descripcionField;
            }
            set {
                this.error_descripcionField = value;
                this.RaisePropertyChanged("error_descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesPortTypeChannel : SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.ServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesPortTypeClient : System.ServiceModel.ClientBase<SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.ServicesPortType>, SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.ServicesPortType {
        
        public ServicesPortTypeClient() {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.tr_lineaCapturaGeneral[] solicitaLineaCapturaGen(SIGAPred.FuentesExternas.Isai.Services.ServiceLC1.tp_lineaCapturaGeneral pregunta) {
            return base.Channel.solicitaLineaCapturaGen(pregunta);
        }
    }
}
