//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPred.FuentesExternas.Isai.Services.ServiceLC2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.1.198.170/soap/lineaCapturaGenWs_secureServer", ConfigurationName="ServiceLC2.lineaCapturaGenWs_secureServerPortType")]
    public interface lineaCapturaGenWs_secureServerPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje solicitaLineaCapturaGenRequest no coincide con el valor predeterminado (http://10.1.198.170/soap/lineaCapturaGenWs_secureServer)
        [System.ServiceModel.OperationContractAttribute(Action="http://10.1.198.170/fut/public/index.php/solicitaLineaCapturaGen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tr_lineaCapturaGeneral))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(detalleCamposMatriz))]
        SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenResponse solicitaLineaCapturaGen(SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.198.170/soap/lineaCapturaGenWs_secureServer")]
    public partial class tp_lineaCapturaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        private int intImpuestoField;
        
        private string referenciaField;
        
        private string fechaLimPPField;
        
        private int totalVField;
        
        private string conceptoField;
        
        private int numPeriodosField;
        
        private string usuarioGenField;
        
        private string ipField;
        
        private detalleCamposMatriz[] arrayDatosField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public int intImpuesto {
            get {
                return this.intImpuestoField;
            }
            set {
                this.intImpuestoField = value;
                this.RaisePropertyChanged("intImpuesto");
            }
        }
        
        /// <remarks/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        public string fechaLimPP {
            get {
                return this.fechaLimPPField;
            }
            set {
                this.fechaLimPPField = value;
                this.RaisePropertyChanged("fechaLimPP");
            }
        }
        
        /// <remarks/>
        public int totalV {
            get {
                return this.totalVField;
            }
            set {
                this.totalVField = value;
                this.RaisePropertyChanged("totalV");
            }
        }
        
        /// <remarks/>
        public string concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("concepto");
            }
        }
        
        /// <remarks/>
        public int numPeriodos {
            get {
                return this.numPeriodosField;
            }
            set {
                this.numPeriodosField = value;
                this.RaisePropertyChanged("numPeriodos");
            }
        }
        
        /// <remarks/>
        public string usuarioGen {
            get {
                return this.usuarioGenField;
            }
            set {
                this.usuarioGenField = value;
                this.RaisePropertyChanged("usuarioGen");
            }
        }
        
        /// <remarks/>
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        /// <remarks/>
        public detalleCamposMatriz[] arrayDatos {
            get {
                return this.arrayDatosField;
            }
            set {
                this.arrayDatosField = value;
                this.RaisePropertyChanged("arrayDatos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.198.170/soap/lineaCapturaGenWs_secureServer")]
    public partial class detalleCamposMatriz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bonificaField;
        
        private string ctaeconumField;
        
        private string ctapredialField;
        
        private string ctarfcField;
        
        private string liquidacionField;
        
        private string id_pagoField;
        
        private string impuestoField;
        
        private string numfolioField;
        
        private string otrosField;
        
        private string recargo1Field;
        
        private string recargo2Field;
        
        private string totalField;
        
        private string vencimField;
        
        /// <remarks/>
        public string bonifica {
            get {
                return this.bonificaField;
            }
            set {
                this.bonificaField = value;
                this.RaisePropertyChanged("bonifica");
            }
        }
        
        /// <remarks/>
        public string ctaeconum {
            get {
                return this.ctaeconumField;
            }
            set {
                this.ctaeconumField = value;
                this.RaisePropertyChanged("ctaeconum");
            }
        }
        
        /// <remarks/>
        public string ctapredial {
            get {
                return this.ctapredialField;
            }
            set {
                this.ctapredialField = value;
                this.RaisePropertyChanged("ctapredial");
            }
        }
        
        /// <remarks/>
        public string ctarfc {
            get {
                return this.ctarfcField;
            }
            set {
                this.ctarfcField = value;
                this.RaisePropertyChanged("ctarfc");
            }
        }
        
        /// <remarks/>
        public string liquidacion {
            get {
                return this.liquidacionField;
            }
            set {
                this.liquidacionField = value;
                this.RaisePropertyChanged("liquidacion");
            }
        }
        
        /// <remarks/>
        public string id_pago {
            get {
                return this.id_pagoField;
            }
            set {
                this.id_pagoField = value;
                this.RaisePropertyChanged("id_pago");
            }
        }
        
        /// <remarks/>
        public string impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }
        
        /// <remarks/>
        public string numfolio {
            get {
                return this.numfolioField;
            }
            set {
                this.numfolioField = value;
                this.RaisePropertyChanged("numfolio");
            }
        }
        
        /// <remarks/>
        public string otros {
            get {
                return this.otrosField;
            }
            set {
                this.otrosField = value;
                this.RaisePropertyChanged("otros");
            }
        }
        
        /// <remarks/>
        public string recargo1 {
            get {
                return this.recargo1Field;
            }
            set {
                this.recargo1Field = value;
                this.RaisePropertyChanged("recargo1");
            }
        }
        
        /// <remarks/>
        public string recargo2 {
            get {
                return this.recargo2Field;
            }
            set {
                this.recargo2Field = value;
                this.RaisePropertyChanged("recargo2");
            }
        }
        
        /// <remarks/>
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        public string vencim {
            get {
                return this.vencimField;
            }
            set {
                this.vencimField = value;
                this.RaisePropertyChanged("vencim");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.198.170/soap/lineaCapturaGenWs_secureServer")]
    public partial class tr_lineaCapturaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int intImpuestoField;
        
        private string referenciaField;
        
        private string lineaCapturaField;
        
        private string rafagaPagoField;
        
        private System.DateTime fcobroField;
        
        private string cajaField;
        
        private string partidaField;
        
        private string dagidField;
        
        private int errorField;
        
        private string error_descripcionField;
        
        /// <remarks/>
        public int intImpuesto {
            get {
                return this.intImpuestoField;
            }
            set {
                this.intImpuestoField = value;
                this.RaisePropertyChanged("intImpuesto");
            }
        }
        
        /// <remarks/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        public string lineaCaptura {
            get {
                return this.lineaCapturaField;
            }
            set {
                this.lineaCapturaField = value;
                this.RaisePropertyChanged("lineaCaptura");
            }
        }
        
        /// <remarks/>
        public string rafagaPago {
            get {
                return this.rafagaPagoField;
            }
            set {
                this.rafagaPagoField = value;
                this.RaisePropertyChanged("rafagaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime fcobro {
            get {
                return this.fcobroField;
            }
            set {
                this.fcobroField = value;
                this.RaisePropertyChanged("fcobro");
            }
        }
        
        /// <remarks/>
        public string caja {
            get {
                return this.cajaField;
            }
            set {
                this.cajaField = value;
                this.RaisePropertyChanged("caja");
            }
        }
        
        /// <remarks/>
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
                this.RaisePropertyChanged("partida");
            }
        }
        
        /// <remarks/>
        public string dagid {
            get {
                return this.dagidField;
            }
            set {
                this.dagidField = value;
                this.RaisePropertyChanged("dagid");
            }
        }
        
        /// <remarks/>
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        public string error_descripcion {
            get {
                return this.error_descripcionField;
            }
            set {
                this.error_descripcionField = value;
                this.RaisePropertyChanged("error_descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitaLineaCapturaGen", WrapperNamespace="", IsWrapped=true)]
    public partial class solicitaLineaCapturaGenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.tp_lineaCapturaGeneral pregunta;
        
        public solicitaLineaCapturaGenRequest() {
        }
        
        public solicitaLineaCapturaGenRequest(SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.tp_lineaCapturaGeneral pregunta) {
            this.pregunta = pregunta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitaLineaCapturaGenResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class solicitaLineaCapturaGenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.tr_lineaCapturaGeneral[] respuesta;
        
        public solicitaLineaCapturaGenResponse() {
        }
        
        public solicitaLineaCapturaGenResponse(SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.tr_lineaCapturaGeneral[] respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface lineaCapturaGenWs_secureServerPortTypeChannel : SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.lineaCapturaGenWs_secureServerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class lineaCapturaGenWs_secureServerPortTypeClient : System.ServiceModel.ClientBase<SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.lineaCapturaGenWs_secureServerPortType>, SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.lineaCapturaGenWs_secureServerPortType {
        
        public lineaCapturaGenWs_secureServerPortTypeClient() {
        }
        
        public lineaCapturaGenWs_secureServerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public lineaCapturaGenWs_secureServerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lineaCapturaGenWs_secureServerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lineaCapturaGenWs_secureServerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenResponse SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.lineaCapturaGenWs_secureServerPortType.solicitaLineaCapturaGen(SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenRequest request) {
            return base.Channel.solicitaLineaCapturaGen(request);
        }
        
        public SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.tr_lineaCapturaGeneral[] solicitaLineaCapturaGen(SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.tp_lineaCapturaGeneral pregunta) {
            SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenRequest inValue = new SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenRequest();
            inValue.pregunta = pregunta;
            SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.solicitaLineaCapturaGenResponse retVal = ((SIGAPred.FuentesExternas.Isai.Services.ServiceLC2.lineaCapturaGenWs_secureServerPortType)(this)).solicitaLineaCapturaGen(inValue);
            return retVal.respuesta;
        }
    }
}
