//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPred.FuentesExternas.Isai.Services.ServiceFUT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.1.65.9/formato_lc/notarios/isai_ws_prueba/isai_ws_server.php", ConfigurationName="ServiceFUT.ServicesPortType")]
    public interface ServicesPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace () of message solicitar_LCRequest does not match the default value (http://10.1.65.9/formato_lc/notarios/isai_ws_prueba/isai_ws_server.php)
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCResponse solicitar_LC(SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.65.9/formato_lc/notarios/isai_ws_prueba/isai_ws_server.php")]
    public partial class tipo_pregunta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        private string usuarioisaiField;
        
        private string passwordisaiField;
        
        private string fechaField;
        
        private int claveField;
        
        private int reduccionField;
        
        private string cuentaField;
        
        private string articuloField;
        
        private string fraccionField;
        
        private string totalField;
        
        private string importeField;
        
        private string operacionField;
        
        private string nombreField;
        
        private string calleynumField;
        
        private string coloniaField;
        
        private string cpField;
        
        private float derechosField;
        
        private float actualizacionField;
        
        private float recargosField;
        
        private float otrosField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string usuarioisai {
            get {
                return this.usuarioisaiField;
            }
            set {
                this.usuarioisaiField = value;
                this.RaisePropertyChanged("usuarioisai");
            }
        }
        
        /// <remarks/>
        public string passwordisai {
            get {
                return this.passwordisaiField;
            }
            set {
                this.passwordisaiField = value;
                this.RaisePropertyChanged("passwordisai");
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        public int clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        public int reduccion {
            get {
                return this.reduccionField;
            }
            set {
                this.reduccionField = value;
                this.RaisePropertyChanged("reduccion");
            }
        }
        
        /// <remarks/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        public string articulo {
            get {
                return this.articuloField;
            }
            set {
                this.articuloField = value;
                this.RaisePropertyChanged("articulo");
            }
        }
        
        /// <remarks/>
        public string fraccion {
            get {
                return this.fraccionField;
            }
            set {
                this.fraccionField = value;
                this.RaisePropertyChanged("fraccion");
            }
        }
        
        /// <remarks/>
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        public string importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
                this.RaisePropertyChanged("operacion");
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        public string calleynum {
            get {
                return this.calleynumField;
            }
            set {
                this.calleynumField = value;
                this.RaisePropertyChanged("calleynum");
            }
        }
        
        /// <remarks/>
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
                this.RaisePropertyChanged("colonia");
            }
        }
        
        /// <remarks/>
        public string cp {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
                this.RaisePropertyChanged("cp");
            }
        }
        
        /// <remarks/>
        public float derechos {
            get {
                return this.derechosField;
            }
            set {
                this.derechosField = value;
                this.RaisePropertyChanged("derechos");
            }
        }
        
        /// <remarks/>
        public float actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        public float recargos {
            get {
                return this.recargosField;
            }
            set {
                this.recargosField = value;
                this.RaisePropertyChanged("recargos");
            }
        }
        
        /// <remarks/>
        public float otros {
            get {
                return this.otrosField;
            }
            set {
                this.otrosField = value;
                this.RaisePropertyChanged("otros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.1.65.9/formato_lc/notarios/isai_ws_prueba/isai_ws_server.php")]
    public partial class tipo_respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string recargoField;
        
        private string cuentaField;
        
        private string impdrecField;
        
        private string actualizacionField;
        
        private string numnotarioField;
        
        private string lineaField;
        
        private string importeField;
        
        private string importe_reducidoField;
        
        private string vigenciaField;
        
        private string totalField;
        
        private string linkfutField;
        
        private string errorField;
        
        private string error_descripcionField;
        
        /// <remarks/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        public string recargo {
            get {
                return this.recargoField;
            }
            set {
                this.recargoField = value;
                this.RaisePropertyChanged("recargo");
            }
        }
        
        /// <remarks/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        public string impdrec {
            get {
                return this.impdrecField;
            }
            set {
                this.impdrecField = value;
                this.RaisePropertyChanged("impdrec");
            }
        }
        
        /// <remarks/>
        public string actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        public string numnotario {
            get {
                return this.numnotarioField;
            }
            set {
                this.numnotarioField = value;
                this.RaisePropertyChanged("numnotario");
            }
        }
        
        /// <remarks/>
        public string linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
                this.RaisePropertyChanged("linea");
            }
        }
        
        /// <remarks/>
        public string importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        public string importe_reducido {
            get {
                return this.importe_reducidoField;
            }
            set {
                this.importe_reducidoField = value;
                this.RaisePropertyChanged("importe_reducido");
            }
        }
        
        /// <remarks/>
        public string vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        /// <remarks/>
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        public string linkfut {
            get {
                return this.linkfutField;
            }
            set {
                this.linkfutField = value;
                this.RaisePropertyChanged("linkfut");
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        public string error_descripcion {
            get {
                return this.error_descripcionField;
            }
            set {
                this.error_descripcionField = value;
                this.RaisePropertyChanged("error_descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitar_LC", WrapperNamespace="", IsWrapped=true)]
    public partial class solicitar_LCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.tipo_pregunta pregunta;
        
        public solicitar_LCRequest() {
        }
        
        public solicitar_LCRequest(SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.tipo_pregunta pregunta) {
            this.pregunta = pregunta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitar_LCResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class solicitar_LCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.tipo_respuesta respuesta;
        
        public solicitar_LCResponse() {
        }
        
        public solicitar_LCResponse(SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.tipo_respuesta respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesPortTypeChannel : SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.ServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesPortTypeClient : System.ServiceModel.ClientBase<SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.ServicesPortType>, SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.ServicesPortType {
        
        public ServicesPortTypeClient() {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCResponse SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.ServicesPortType.solicitar_LC(SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCRequest request) {
            return base.Channel.solicitar_LC(request);
        }
        
        public SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.tipo_respuesta solicitar_LC(SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.tipo_pregunta pregunta) {
            SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCRequest inValue = new SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCRequest();
            inValue.pregunta = pregunta;
            SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.solicitar_LCResponse retVal = ((SIGAPred.FuentesExternas.Isai.Services.ServiceFUT.ServicesPortType)(this)).solicitar_LC(inValue);
            return retVal.respuesta;
        }
    }
}
